services:
  # bind mount example
  linuxgsm-onset-bind:
    image: gameservermanagers/gameserver:onset
    # image: ghcr.io/gameservermanagers/gameserver:onset
    # expose all ports directly
    network_mode: host
    container_name: onsetserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/onsetserver:/data

  # volume example
  linuxgsm-onset-volume:
    image: gameservermanagers/gameserver:onset
    # image: ghcr.io/gameservermanagers/gameserver:onset
    container_name: onsetserver
    network_mode: host
    volumes:
      - linuxgsm-onset:/data

volumes:
  linuxgsm-onset:
