services:
  # bind mount example
  linuxgsm-ts-bind:
    image: gameservermanagers/gameserver:ts
    # image: ghcr.io/gameservermanagers/gameserver:ts
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    container_name: tsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/tsserver:/data

  # volume example
  linuxgsm-ts-volume:
    image: gameservermanagers/gameserver:ts
    # image: ghcr.io/gameservermanagers/gameserver:ts
    container_name: tsserver
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    volumes:
      - linuxgsm-ts:/data

volumes:
  linuxgsm-ts:
