services:
  # bind mount example
  linuxgsm-tf-bind:
    image: gameservermanagers/gameserver:tf
    # image: ghcr.io/gameservermanagers/gameserver:tf
    ports:
      - '5001:5001' # port
      - '5002:5002' # beaconport
      - '5003:5003' # shutdownport
      - '27015:27015' # queryport
    container_name: tfserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/tfserver:/data

  # volume example
  linuxgsm-tf-volume:
    image: gameservermanagers/gameserver:tf
    # image: ghcr.io/gameservermanagers/gameserver:tf
    container_name: tfserver
    ports:
      - '5001:5001' # port
      - '5002:5002' # beaconport
      - '5003:5003' # shutdownport
      - '27015:27015' # queryport
    volumes:
      - linuxgsm-tf:/data

volumes:
  linuxgsm-tf:
