services:
  # bind mount example
  linuxgsm-q4-bind:
    image: gameservermanagers/gameserver:q4
    # image: ghcr.io/gameservermanagers/gameserver:q4
    ports:
      - '28004:28004' # port
    container_name: q4server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/q4server:/data

  # volume example
  linuxgsm-q4-volume:
    image: gameservermanagers/gameserver:q4
    # image: ghcr.io/gameservermanagers/gameserver:q4
    container_name: q4server
    ports:
      - '28004:28004' # port
    volumes:
      - linuxgsm-q4:/data

volumes:
  linuxgsm-q4:
