services:
  # bind mount example
  linuxgsm-cmw-bind:
    image: gameservermanagers/gameserver:cmw
    # image: ghcr.io/gameservermanagers/gameserver:cmw
    ports:
      - '7777:7777' # port
      - '7779:7779' # queryport
    container_name: cmwserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/cmwserver:/data

  # volume example
  linuxgsm-cmw-volume:
    image: gameservermanagers/gameserver:cmw
    # image: ghcr.io/gameservermanagers/gameserver:cmw
    container_name: cmwserver
    ports:
      - '7777:7777' # port
      - '7779:7779' # queryport
    volumes:
      - linuxgsm-cmw:/data

volumes:
  linuxgsm-cmw:
