services:
  # bind mount example
  linuxgsm-ut2k4-bind:
    image: gameservermanagers/gameserver:ut2k4
    # image: ghcr.io/gameservermanagers/gameserver:ut2k4
    # expose all ports directly
    network_mode: host
    container_name: ut2k4server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ut2k4server:/data

  # volume example
  linuxgsm-ut2k4-volume:
    image: gameservermanagers/gameserver:ut2k4
    # image: ghcr.io/gameservermanagers/gameserver:ut2k4
    container_name: ut2k4server
    network_mode: host
    volumes:
      - linuxgsm-ut2k4:/data

volumes:
  linuxgsm-ut2k4:
