services:
  # bind mount example
  linuxgsm-unt-bind:
    image: gameservermanagers/gameserver:unt
    # image: ghcr.io/gameservermanagers/gameserver:unt
    ports:
      - '27015:27015' # port
    container_name: untserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/untserver:/data

  # volume example
  linuxgsm-unt-volume:
    image: gameservermanagers/gameserver:unt
    # image: ghcr.io/gameservermanagers/gameserver:unt
    container_name: untserver
    ports:
      - '27015:27015' # port
    volumes:
      - linuxgsm-unt:/data

volumes:
  linuxgsm-unt:
