services:
  # bind mount example
  linuxgsm-q3-bind:
    image: gameservermanagers/gameserver:q3
    # image: ghcr.io/gameservermanagers/gameserver:q3
    ports:
      - '27960:27960' # port
    container_name: q3server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/q3server:/data

  # volume example
  linuxgsm-q3-volume:
    image: gameservermanagers/gameserver:q3
    # image: ghcr.io/gameservermanagers/gameserver:q3
    container_name: q3server
    ports:
      - '27960:27960' # port
    volumes:
      - linuxgsm-q3:/data

volumes:
  linuxgsm-q3:
