services:
  # bind mount example
  linuxgsm-terraria-bind:
    image: gameservermanagers/gameserver:terraria
    # image: ghcr.io/gameservermanagers/gameserver:terraria
    # expose all ports directly
    network_mode: host
    container_name: terrariaserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/terrariaserver:/data

  # volume example
  linuxgsm-terraria-volume:
    image: gameservermanagers/gameserver:terraria
    # image: ghcr.io/gameservermanagers/gameserver:terraria
    container_name: terrariaserver
    network_mode: host
    volumes:
      - linuxgsm-terraria:/data

volumes:
  linuxgsm-terraria:
