services:
  # bind mount example
  linuxgsm-cc-bind:
    image: gameservermanagers/gameserver:cc
    # image: ghcr.io/gameservermanagers/gameserver:cc
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
      - '27020:27020' # sourcetvport
    container_name: ccserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ccserver:/data

  # volume example
  linuxgsm-cc-volume:
    image: gameservermanagers/gameserver:cc
    # image: ghcr.io/gameservermanagers/gameserver:cc
    container_name: ccserver
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
      - '27020:27020' # sourcetvport
    volumes:
      - linuxgsm-cc:/data

volumes:
  linuxgsm-cc:
