services:
  # bind mount example
  linuxgsm-inss-bind:
    image: gameservermanagers/gameserver:inss
    # image: ghcr.io/gameservermanagers/gameserver:inss
    ports:
      - '27102:27102' # port
      - '27131:27131' # queryport
      - '27015:27015' # rconport
    container_name: inssserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/inssserver:/data

  # volume example
  linuxgsm-inss-volume:
    image: gameservermanagers/gameserver:inss
    # image: ghcr.io/gameservermanagers/gameserver:inss
    container_name: inssserver
    ports:
      - '27102:27102' # port
      - '27131:27131' # queryport
      - '27015:27015' # rconport
    volumes:
      - linuxgsm-inss:/data

volumes:
  linuxgsm-inss:
