services:
  # bind mount example
  linuxgsm-dodr-bind:
    image: gameservermanagers/gameserver:dodr
    # image: ghcr.io/gameservermanagers/gameserver:dodr
    ports:
      - '7777:7777' # port
      - '27015:27015' # queryport
    container_name: dodrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/dodrserver:/data

  # volume example
  linuxgsm-dodr-volume:
    image: gameservermanagers/gameserver:dodr
    # image: ghcr.io/gameservermanagers/gameserver:dodr
    container_name: dodrserver
    ports:
      - '7777:7777' # port
      - '27015:27015' # queryport
    volumes:
      - linuxgsm-dodr:/data

volumes:
  linuxgsm-dodr:
