services:
  # bind mount example
  linuxgsm-sdtd-bind:
    image: gameservermanagers/gameserver:sdtd
    # image: ghcr.io/gameservermanagers/gameserver:sdtd
    # expose all ports directly
    network_mode: host
    container_name: sdtdserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/sdtdserver:/data

  # volume example
  linuxgsm-sdtd-volume:
    image: gameservermanagers/gameserver:sdtd
    # image: ghcr.io/gameservermanagers/gameserver:sdtd
    container_name: sdtdserver
    network_mode: host
    volumes:
      - linuxgsm-sdtd:/data

volumes:
  linuxgsm-sdtd:
