services:
  # bind mount example
  linuxgsm-av-bind:
    image: gameservermanagers/gameserver:av
    # image: ghcr.io/gameservermanagers/gameserver:av
    # expose all ports directly
    network_mode: host
    container_name: avserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/avserver:/data

  # volume example
  linuxgsm-av-volume:
    image: gameservermanagers/gameserver:av
    # image: ghcr.io/gameservermanagers/gameserver:av
    container_name: avserver
    network_mode: host
    volumes:
      - linuxgsm-av:/data

volumes:
  linuxgsm-av:
