services:
  # bind mount example
  linuxgsm-cs2-bind:
    image: gameservermanagers/gameserver:cs2
    # image: ghcr.io/gameservermanagers/gameserver:cs2
    ports:
      - '27015:27015' # port
    container_name: cs2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/cs2server:/data

  # volume example
  linuxgsm-cs2-volume:
    image: gameservermanagers/gameserver:cs2
    # image: ghcr.io/gameservermanagers/gameserver:cs2
    container_name: cs2server
    ports:
      - '27015:27015' # port
    volumes:
      - linuxgsm-cs2:/data

volumes:
  linuxgsm-cs2:
