services:
  # bind mount example
  linuxgsm-samp-bind:
    image: gameservermanagers/gameserver:samp
    # image: ghcr.io/gameservermanagers/gameserver:samp
    ports:
      - '7777:7777' # port
    container_name: sampserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/sampserver:/data

  # volume example
  linuxgsm-samp-volume:
    image: gameservermanagers/gameserver:samp
    # image: ghcr.io/gameservermanagers/gameserver:samp
    container_name: sampserver
    ports:
      - '7777:7777' # port
    volumes:
      - linuxgsm-samp:/data

volumes:
  linuxgsm-samp:
