services:
  # bind mount example
  linuxgsm-pmc-bind:
    image: gameservermanagers/gameserver:pmc
    # image: ghcr.io/gameservermanagers/gameserver:pmc
    # expose all ports directly
    network_mode: host
    container_name: pmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/pmcserver:/data

  # volume example
  linuxgsm-pmc-volume:
    image: gameservermanagers/gameserver:pmc
    # image: ghcr.io/gameservermanagers/gameserver:pmc
    container_name: pmcserver
    network_mode: host
    volumes:
      - linuxgsm-pmc:/data

volumes:
  linuxgsm-pmc:
