services:
  # bind mount example
  linuxgsm-jk2-bind:
    image: gameservermanagers/gameserver:jk2
    # image: ghcr.io/gameservermanagers/gameserver:jk2
    ports:
      - '27960:27960' # port
    container_name: jk2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/jk2server:/data

  # volume example
  linuxgsm-jk2-volume:
    image: gameservermanagers/gameserver:jk2
    # image: ghcr.io/gameservermanagers/gameserver:jk2
    container_name: jk2server
    ports:
      - '27960:27960' # port
    volumes:
      - linuxgsm-jk2:/data

volumes:
  linuxgsm-jk2:
