services:
  # bind mount example
  linuxgsm-mta-bind:
    image: gameservermanagers/gameserver:mta
    # image: ghcr.io/gameservermanagers/gameserver:mta
    # expose all ports directly
    network_mode: host
    container_name: mtaserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/mtaserver:/data

  # volume example
  linuxgsm-mta-volume:
    image: gameservermanagers/gameserver:mta
    # image: ghcr.io/gameservermanagers/gameserver:mta
    container_name: mtaserver
    network_mode: host
    volumes:
      - linuxgsm-mta:/data

volumes:
  linuxgsm-mta:
