services:
  # bind mount example
  linuxgsm-bd-bind:
    image: gameservermanagers/gameserver:bd
    # image: ghcr.io/gameservermanagers/gameserver:bd
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    container_name: bdserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/bdserver:/data

  # volume example
  linuxgsm-bd-volume:
    image: gameservermanagers/gameserver:bd
    # image: ghcr.io/gameservermanagers/gameserver:bd
    container_name: bdserver
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    volumes:
      - linuxgsm-bd:/data

volumes:
  linuxgsm-bd:
