services:
  # bind mount example
  linuxgsm-bf1942-bind:
    image: gameservermanagers/gameserver:bf1942
    # image: ghcr.io/gameservermanagers/gameserver:bf1942
    # expose all ports directly
    network_mode: host
    container_name: bf1942server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/bf1942server:/data

  # volume example
  linuxgsm-bf1942-volume:
    image: gameservermanagers/gameserver:bf1942
    # image: ghcr.io/gameservermanagers/gameserver:bf1942
    container_name: bf1942server
    network_mode: host
    volumes:
      - linuxgsm-bf1942:/data

volumes:
  linuxgsm-bf1942:
