services:
  # bind mount example
  linuxgsm-dmc-bind:
    image: gameservermanagers/gameserver:dmc
    # image: ghcr.io/gameservermanagers/gameserver:dmc
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    container_name: dmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/dmcserver:/data

  # volume example
  linuxgsm-dmc-volume:
    image: gameservermanagers/gameserver:dmc
    # image: ghcr.io/gameservermanagers/gameserver:dmc
    container_name: dmcserver
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    volumes:
      - linuxgsm-dmc:/data

volumes:
  linuxgsm-dmc:
