services:
  # bind mount example
  linuxgsm-ahl-bind:
    image: gameservermanagers/gameserver:ahl
    # image: ghcr.io/gameservermanagers/gameserver:ahl
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    container_name: ahlserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ahlserver:/data

  # volume example
  linuxgsm-ahl-volume:
    image: gameservermanagers/gameserver:ahl
    # image: ghcr.io/gameservermanagers/gameserver:ahl
    container_name: ahlserver
    ports:
      - '27015:27015' # port
      - '27005:27005' # clientport
    volumes:
      - linuxgsm-ahl:/data

volumes:
  linuxgsm-ahl:
