services:
  # bind mount example
  linuxgsm-ets2-bind:
    image: gameservermanagers/gameserver:ets2
    # image: ghcr.io/gameservermanagers/gameserver:ets2
    # expose all ports directly
    network_mode: host
    container_name: ets2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ets2server:/data

  # volume example
  linuxgsm-ets2-volume:
    image: gameservermanagers/gameserver:ets2
    # image: ghcr.io/gameservermanagers/gameserver:ets2
    container_name: ets2server
    network_mode: host
    volumes:
      - linuxgsm-ets2:/data

volumes:
  linuxgsm-ets2:
