services:
  # bind mount example
  linuxgsm-wf-bind:
    image: gameservermanagers/gameserver:wf
    # image: ghcr.io/gameservermanagers/gameserver:wf
    ports:
      - '44400:44400' # port
      - '44444:44444' # httpport
    container_name: wfserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/wfserver:/data

  # volume example
  linuxgsm-wf-volume:
    image: gameservermanagers/gameserver:wf
    # image: ghcr.io/gameservermanagers/gameserver:wf
    container_name: wfserver
    ports:
      - '44400:44400' # port
      - '44444:44444' # httpport
    volumes:
      - linuxgsm-wf:/data

volumes:
  linuxgsm-wf:
